all:
	./compile.sh
	./compile.sh

.PHONY: clean

clean:
	@echo Cleaning files...
	@rm -f tcc.pdf tcc.aux tcc.idx tcc.lof tcc.toc tcc.log tcc.lot setup.log tcc.bbl tcc.blg tcc.brf tcc.out.ps tcc.dvi tcc.fdb_latexmk tcc.fls tcc.ilg tcc.ind
	rm -f *~ *.dvi *.ps *.backup *.aux *.log
	rm -f *.lof *.lot *.bbl *.blg *.brf *.toc *.idx
	rm -f ./figuras/produto/*.pdf