# Generated by Django 2.1.1 on 2018-10-11 13:48

import classificador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2)),
                ('id_semg', models.IntegerField()),
                ('result', models.IntegerField(blank=True, null=True)),
                ('fileSelected', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SemgFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado', models.FileField(upload_to=classificador.models.SemgFile._get_upload_to)),
            ],
        ),
    ]
