# Generated by Django 2.1.1 on 2018-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='arquivar',
            field=models.BooleanField(default=False),
        ),
    ]
