# Generated by Django 2.1.1 on 2018-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2),
        ),
    ]
