# Generated by Django 2.1.1 on 2018-10-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
