# Generated by Django 2.1.1 on 2018-10-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0002_patient_arquivar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fileSelected',
            field=models.TextField(blank=True, null=True),
        ),
    ]
