# Generated by Django 2.1.1 on 2018-09-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0002_auto_20180925_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='dado',
            field=models.FileField(default=1, upload_to='df_dados'),
            preserve_default=False,
        ),
    ]
