# Generated by Django 2.1.1 on 2018-09-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0003_feature_dado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='dado',
            field=models.FileField(upload_to='edf'),
        ),
    ]
