# Generated by Django 2.1.1 on 2018-10-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0003_auto_20181025_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_semg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
