# Generated by Django 2.1.1 on 2018-09-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0004_auto_20180925_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='dado',
            field=models.FileField(default=None, upload_to='edf'),
        ),
    ]
