# Generated by Django 2.1.1 on 2018-09-30 14:47

import classificador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0005_auto_20180925_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='dado',
            field=models.FileField(default=None, upload_to=classificador.models.Feature._get_upload_to),
        ),
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
