# Generated by Django 2.1.1 on 2018-10-02 15:16

import classificador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0006_auto_20180930_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='dado',
            field=models.FileField(upload_to=classificador.models.Feature._get_upload_to),
        ),
    ]
