# Generated by Django 2.1.1 on 2018-10-03 21:48

import classificador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificador', '0008_feature_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='dado',
            field=models.FileField(blank=True, null=True, upload_to=classificador.models.Feature._get_upload_to),
        ),
    ]
