export const BUSCAR_PACIENTES = 'BUSCAR_PACIENTES'
export const CADASTRAR_PACIENTES = 'CADASTRAR_PACIENTES'
export const EDITAR_PACIENTES = 'EDITAR_PACIENTES'
export const ARQUIVAR_PACIENTES = 'ARQUIVAR_PACIENTES'